name: Deploy Spring Boot to Elastic Beanstalk

on:
        push:
                branches:
                        - main # Or your desired branch

jobs:
        build-and-deploy:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout code
                          uses: actions/checkout@v4

                        - name: Set up Java
                          uses: actions/setup-java@v4
                          with:
                                  distribution: 'corretto' # Or your preferred Java distribution
                                  java-version: '17' # Or your application's Java version

                        - name: Build with Maven
                          run: mvn clean package -DskipTests

                        - name: Create Elastic Beanstalk Application
                          run: |
                                  if ! aws elasticbeanstalk describe-applications --application-names sboot-demo-app --query 'Applications[?ApplicationName==`sboot-demo-app`]' --output text | grep -q sboot-demo-app; then
                                    echo "Application does not exist, creating..."
                                    aws elasticbeanstalk create-application --application-name sboot-demo-app --description "Spring Boot Demo Application"
                                  else
                                    echo "Application already exists"
                                  fi
                          env:
                                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                                  AWS_DEFAULT_REGION: us-east-1

                        - name: Create Elastic Beanstalk Environment
                          run: |
                                  if ! aws elasticbeanstalk describe-environments --application-name sboot-demo-app --environment-names sboot-demo-env --query 'Environments[?EnvironmentName==`sboot-demo-env`]' --output text | grep -q sboot-demo-env; then
                                    echo "Environment does not exist, creating..."
                                    # Get the latest Java Corretto solution stack
                                    SOLUTION_STACK=$(aws elasticbeanstalk list-available-solution-stacks --query 'SolutionStacks[?contains(@, `Corretto 17`) && contains(@, `64bit`)][0]' --output text)
                                    if [ -z "$SOLUTION_STACK" ]; then
                                      # Fallback to a common stack name
                                      SOLUTION_STACK="64bit Amazon Linux 2 v3.6.0 running Corretto 17"
                                    fi
                                    echo "Using solution stack: $SOLUTION_STACK"
                                    aws elasticbeanstalk create-environment \
                                      --application-name sboot-demo-app \
                                      --environment-name sboot-demo-env \
                                      --solution-stack-name "$SOLUTION_STACK" \
                                      --description "Spring Boot Demo Environment"
                                    echo "Waiting for environment to be ready..."
                                    aws elasticbeanstalk wait environment-exists --environment-names sboot-demo-env
                                  else
                                    echo "Environment already exists"
                                  fi
                          env:
                                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                                  AWS_DEFAULT_REGION: us-east-1

                        - name: Deploy to Elastic Beanstalk
                          uses: einaregilsson/beanstalk-deploy@v21
                          with:
                                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                                  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                                  application_name: sboot-demo-app
                                  environment_name: sboot-demo-env
                                  version_label: ${{ github.sha }}
                                  region: us-east-1
                                  deployment_package: target/demo-0.0.1-SNAPSHOT.jar